# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

addons:
  apt:
    packages:
      #- python2.7       # comment this to use python3
      - python3        # uncomment this to use python3

before_install:

  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install numerizer
  - sudo apt-get update
